### PR TITLE
Resolve issue with locating workbench path in newer VS Code

### LINKED ISSUE #355: Neon Dreams stopped working in VS
Hey everyone, hope you're doing well!
Today, when launching VS Code, I encountered the following error:

> Neon Dreams was unable to modify the core VS code files needed to launch the extension.
> You may need to run VS Code with admin privileges in order to enable Neon Dreams.

I tried running VS Code as an administrator, but the issue still persists.
I'm currently on VS Code version **1.102.0**.

Has anyone else run into this recently?
Any suggestions or fixes would be greatly appreciated!

Thanks in advance! 🙏

### PR DESCRIPTION
**Pull request by mcpads**
Fix #355 #354 

In VSCode version 1.102 (see commit cdf404ff4), the Electron base path was reverted from electron-sandbox back to electron-browser.

To accommodate this and improve future compatibility, this change dynamically checks for the correct workbench file path instead of relying on a VSCode version check.

### CODE REVIEW

File: src/extension.js [hunk 1]
```diff
@@ -23,9 +23,8 @@ function activate(context) {
 	let disposable = vscode.commands.registerCommand('synthwave84.enableNeon', function () {
 
 		const appDir = path.dirname(vscode.env.appRoot);
-		const base = path.join(appDir,'app','out','vs','code');
-		const electronBase = isVSCodeBelowVersion("1.70.0") ? "electron-browser" : "electron-sandbox";
-		const workBenchFilename = vscode.version == "1.94.0" ? "workbench.esm.html" : "workbench.html";
+		const base = path.join(appDir, 'app', 'out', 'vs', 'code');
+		const [electronBase, workBenchFilename] = resolveWorkbenchPaths(base);
```
Comment (robb0wen) [inline src/extension.js]: If the resolveWorkbenchPaths function ever returns null, array destructuring will throw an uncaught `null is not iterable` error. Perhaps it might be best to move the start of the `try` to the start of the enclosing function, around line 24

File: src/extension.js [hunk 2]
```diff
@@ -96,8 +95,7 @@ function deactivate() {
 function uninstall() {
 	const appDir = path.dirname(vscode.env.appRoot);
 	const base = path.join(appDir, 'app', 'out', 'vs', 'code');
-	const electronBase = isVSCodeBelowVersion("1.70.0") ? "electron-browser" : "electron-sandbox";
-	const workBenchFilename = vscode.version == "1.94.0" ? "workbench.esm.html" : "workbench.html";
+	const [electronBase, workBenchFilename] = resolveWorkbenchPaths(base);
```
Comment (robb0wen) [inline src/extension.js]: Similar to the previous comment, it'd be worth wrapping the uninstall in a try-catch too.

**Comment by robb0wen** [comment]
Thanks for looking at this issue - this is a nice solution! I left a couple of comments around error handling, if you have time to make the updates, but otherwise it's looking good.

**Comment by mcpads** [comment]
Thanks for the feedback, @robb0wen
I've updated the code to improve the error handling. Please take another look.

**Review by robb0wen — APPROVED** [review]

**Comment by robb0wen** [comment]
Love it. Thanks for updating. That's all merged in!
